### PR TITLE
Copy tweak

### PR DESCRIPTION
**Pull request by lynnandtonic**
This PR:

- Removes "three" from number of steps https://github.com/fostive/wicked-coolkit-user/issues/32
- Adds "free" to creating Salesforce instance step https://github.com/fostive/wicked-coolkit-user/issues/31
- Moves optional steps into a callout https://github.com/fostive/wicked-coolkit-user/issues/34

image

### CODE REVIEW

**Comment by lynnandtonic** [comment]
For this issue: https://github.com/fostive/wicked-coolkit-user/issues/34

image

**Comment by crcastle** [comment]
@lynnandtonic this looks great!

To further simplify, @julianduque suggested that we could add an "Import Sticker Data" button to the area of the Trading Card tab where the stickers are shown. This would change step 4 to be something as simple as "Click 'Import Sticker Data' button".

I'll work on that change now and paste a screen recording here so you can see what the process will be like.

**Comment by crcastle** [comment]
@lynnandtonic here's a new process for sticker data import. What do you think?

When the user clicks the button, it grabs the CSV from https://unpkg.com/wicked-coolkit@^1.0.1/dist/stickers/stickers.csv and imports the records from the CSV into Salesforce.

https://user-images.githubusercontent.com/275734/106987028-9de92b00-673a-11eb-9cd0-3282c148b0b3.mp4

Implemented in https://github.com/fostive/wicked-coolkit-salesforce-app/pull/44

**Comment by lynnandtonic** [comment]
@crcastle Perfecto! I'll get the copy updated to match.

**Comment by lynnandtonic** [comment]
@crcastle Here are those changes we discussed. Would love your reaction to them!

First, I moved the Help link into the header and changed it to Coolkit Admin. Do you think this makes it more clear?

image

Then for the /getting-started page:
- Chunked the items into visual sections
- Made note of needing a "new" Salesforce Dev instance
- Removed step about sticker import
- Moved GitHub call to action to a top bar
- Added a basic new footer with a couple links

How does this feel?

image

**Review by crcastle — COMMENTED** [review]
looks good 🙌

**Review by crcastle — APPROVED** [review]
👍

**Pull request merged**
