### PR TITLE
getting-started links open in new windows

### PR DESCRIPTION
**Pull request by lynnandtonic**
image

### CODE REVIEW

**Comment by lynnandtonic** [comment]
I'm wondering if the buttons should open in new windows also?

**Comment by lynnandtonic** [comment]
@crcastle Ok I made a couple other changes:

- Buttons link to new windows as well
- Added a Help link to the footer links which goes to /getting-started (previously the "Developer Trading Card" link in the header did that, but now it links to root)

**Comment by crcastle** [comment]
@lynnandtonic are you asking about the buttons on https://www.wickedcoolkit.com/ ? I was kind of wondering that too... but then thought that really the buttons just need maybe a parenthetical below them or maybe a fancy tooltip that says something like "Deploy the Heroku app (free) and then click 'View App'".

**Comment by lynnandtonic** [comment]
@crcastle ok cool I can add that there

**Comment by lynnandtonic** [comment]
@crcastle This one is good to merge if you're good with it. I made a separate issue https://github.com/fostive/wickedcoolkit.com/issues/67 for me to add that info to the main site deploy buttons

**Review by crcastle — APPROVED** [review]
👍

**Pull request merged**
